services:
  app-dev:
    build: .
    depends_on:
      - db-dev
    extends:
      file: docker-compose.yml
      service: app
    environment:
      - RUST_LOG=debug
      - CARGO_INCREMENTAL=1
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: cargo watch -x run

  db-dev:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  cargo-cache:
  target-cache:
