-- Add migration script here
CREATE TABLE USERS(
    ID UUID UNIQUE NOT NULL,
    PRIMARY KEY (ID),
    EMAIL TEXT NOT NULL UNIQUE,
    NAME TEXT UNIQUE NOT NULL,
    PASSWORD TEXT UNIQUE NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL
);
